BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TextClipCategory" (
	"Oid"	INTEGER,
	"Title"	TEXT,
	"ParentOid"	INTEGER DEFAULT 0,
	PRIMARY KEY("Oid" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TextClip" (
	"Oid"	INTEGER,
	"TextChunk"	TEXT,
	"CategoryOid"	INTEGER DEFAULT 0,
	PRIMARY KEY("Oid" AUTOINCREMENT)
);
COMMIT;
